services:
  test-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: test
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
    ports:
      - '3307:3307'
    command: --default-authentication-plugin=mysql_native_password
