name: ci
on:
  push:
    branches:
      - develop

  pull_request:
    branches:
      - develop
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: mirromutth/mysql-action@v1.1
        with:
          host port: 3306
          character set server: 'utf8'
          collation server: 'utf8_general_ci'
          mysql version: '8.0'
          mysql database: 'test'
          mysql root password: 1234
          mysql user: 'root'
          mysql password: 1234
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install pnpm
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Lint
        run: pnpm eslint

      - name: Test
        run: pnpm test

      - name: E2E Test
        run: pnpm test:e2e

      - name: Push CI Result on Slack
        uses: 8398a7/action-slack@v3
        with:
          author_name: '[SERVER] IMKDW DEV CI Result'
          status: ${{ job.status }}
          fields: repo,message,author,took
          text: ${{ steps.set_text.outputs.text }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
