name: ci
on:
  push:
    branches:
      - develop

  pull_request:
    branches:
      - develop
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    services:
      test-db:
        image: mysql:8.0
        environment:
        MYSQL_ROOT_PASSWORD: 1234
        MYSQL_DATABASE: test
        MYSQL_USER: root
        MYSQL_PASSWORD: 1234
    ports:
      - '3306:3306'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install IMKDW-Dev
        run: pnpm install

      - name: Compile IMKDW-Dev
        run: pnpm build

      - name: Validate through EsLint
        run: pnpm eslint

      - name: Test IMKDW-Dev
        run: pnpm test

      - name: CI 결과 슬랙에 푸쉬
        uses: 8398a7/action-slack@v3
        with:
          author_name: '[SERVER] IMKDW DEV CI Result'
          status: ${{ job.status }}
          fields: repo,message,author,took
          text: ${{ steps.set_text.outputs.text }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
